# Generated by Django 5.0.4 on 2024-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_userdetails_cognito_user_userdetails_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteCity',
        ),
    ]
