# Generated by Django 5.0.4 on 2024-05-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
